/**
 * LEVEL UP — List of Countries, Phone Codes and Cities
 */

export const COUNTRIES = [
  { name: 'Azerbaijan', code: 'AZ', phoneCode: '+994' },
  { name: 'Turkey', code: 'TR', phoneCode: '+90' },
  { name: 'Russia', code: 'RU', phoneCode: '+7' },
  { name: 'United States', code: 'US', phoneCode: '+1' },
  { name: 'Germany', code: 'DE', phoneCode: '+49' },
  { name: 'France', code: 'FR', phoneCode: '+33' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44' },
  { name: 'Italy', code: 'IT', phoneCode: '+39' },
  { name: 'Spain', code: 'ES', phoneCode: '+34' },
  { name: 'Canada', code: 'CA', phoneCode: '+1' },
  { name: 'Georgia', code: 'GE', phoneCode: '+995' },
  { name: 'Ukraine', code: 'UA', phoneCode: '+380' },
  { name: 'Kazakhstan', code: 'KZ', phoneCode: '+7' },
  { name: 'Uzbekistan', code: 'UZ', phoneCode: '+998' },
  { name: 'Turkmenistan', code: 'TM', phoneCode: '+993' },
  { name: 'Kyrgyzstan', code: 'KG', phoneCode: '+996' },
  { name: 'Tajikistan', code: 'TJ', phoneCode: '+992' },
  { name: 'Belarus', code: 'BY', phoneCode: '+375' },
  { name: 'Moldova', code: 'MD', phoneCode: '+373' },
  { name: 'Iran', code: 'IR', phoneCode: '+98' },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '+966' },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '+971' },
  { name: 'Qatar', code: 'QA', phoneCode: '+974' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965' },
  { name: 'Bahrain', code: 'BH', phoneCode: '+973' },
  { name: 'Oman', code: 'OM', phoneCode: '+968' },
  { name: 'Jordan', code: 'JO', phoneCode: '+962' },
  { name: 'Lebanon', code: 'LB', phoneCode: '+961' },
  { name: 'Iraq', code: 'IQ', phoneCode: '+964' },
  { name: 'Syria', code: 'SY', phoneCode: '+963' },
  { name: 'Israel', code: 'IL', phoneCode: '+972' },
  { name: 'Poland', code: 'PL', phoneCode: '+48' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420' },
  { name: 'Slovakia', code: 'SK', phoneCode: '+421' },
  { name: 'Hungary', code: 'HU', phoneCode: '+36' },
  { name: 'Romania', code: 'RO', phoneCode: '+40' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359' },
  { name: 'Greece', code: 'GR', phoneCode: '+30' },
  { name: 'Cyprus', code: 'CY', phoneCode: '+357' },
  { name: 'Austria', code: 'AT', phoneCode: '+43' },
  { name: 'Belgium', code: 'BE', phoneCode: '+32' },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31' },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41' },
  { name: 'Sweden', code: 'SE', phoneCode: '+46' },
  { name: 'Norway', code: 'NO', phoneCode: '+47' },
  { name: 'Denmark', code: 'DK', phoneCode: '+45' },
  { name: 'Finland', code: 'FI', phoneCode: '+358' },
  { name: 'Ireland', code: 'IE', phoneCode: '+353' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351' },
  { name: 'India', code: 'IN', phoneCode: '+91' },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880' },
  { name: 'China', code: 'CN', phoneCode: '+86' },
  { name: 'Japan', code: 'JP', phoneCode: '+81' },
  { name: 'South Korea', code: 'KR', phoneCode: '+82' },
  { name: 'North Korea', code: 'KP', phoneCode: '+850' },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84' },
  { name: 'Thailand', code: 'TH', phoneCode: '+66' },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62' },
  { name: 'Malaysia', code: 'MY', phoneCode: '+60' },
  { name: 'Singapore', code: 'SG', phoneCode: '+65' },
  { name: 'Philippines', code: 'PH', phoneCode: '+63' },
  { name: 'Australia', code: 'AU', phoneCode: '+61' },
  { name: 'New Zealand', code: 'NZ', phoneCode: '+64' },
  { name: 'Brazil', code: 'BR', phoneCode: '+55' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Chile', code: 'CL', phoneCode: '+56' },
  { name: 'Colombia', code: 'CO', phoneCode: '+57' },
  { name: 'Peru', code: 'PE', phoneCode: '+51' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58' },
  { name: 'Mexico', code: 'MX', phoneCode: '+52' },
  { name: 'Egypt', code: 'EG', phoneCode: '+20' },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234' },
  { name: 'Kenya', code: 'KE', phoneCode: '+254' },
  { name: 'Morocco', code: 'MA', phoneCode: '+212' },
  { name: 'Algeria', code: 'DZ', phoneCode: '+213' },
  { name: 'Tunisia', code: 'TN', phoneCode: '+216' },
  { name: 'Libya', code: 'LY', phoneCode: '+218' },
  { name: 'Sudan', code: 'SD', phoneCode: '+249' },
  { name: 'Ethiopia', code: 'ET', phoneCode: '+251' },
  { name: 'Ghana', code: 'GH', phoneCode: '+233' },
  { name: 'Angola', code: 'AO', phoneCode: '+244' },
  { name: 'Mozambique', code: 'MZ', phoneCode: '+258' },
  { name: 'Madagascar', code: 'MG', phoneCode: '+261' },
  { name: 'Senegal', code: 'SN', phoneCode: '+221' },
  { name: 'Zimbabwe', code: 'ZW', phoneCode: '+263' },
  { name: 'Croatia', code: 'HR', phoneCode: '+385' },
  { name: 'Serbia', code: 'RS', phoneCode: '+381' },
  { name: 'Slovenia', code: 'SI', phoneCode: '+386' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phoneCode: '+387' },
  { name: 'Albania', code: 'AL', phoneCode: '+355' },
  { name: 'North Macedonia', code: 'MK', phoneCode: '+389' },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382' },
  { name: 'Iceland', code: 'IS', phoneCode: '+354' },
  { name: 'Estonia', code: 'EE', phoneCode: '+372' },
  { name: 'Latvia', code: 'LV', phoneCode: '+371' },
  { name: 'Lithuania', code: 'LT', phoneCode: '+370' },
  { name: 'Luxembourg', code: 'LU', phoneCode: '+352' },
  { name: 'Malta', code: 'MT', phoneCode: '+356' },
  { name: 'Monaco', code: 'MC', phoneCode: '+377' },
  { name: 'Andorra', code: 'AD', phoneCode: '+376' },
  { name: 'San Marino', code: 'SM', phoneCode: '+378' },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '+423' },
  { name: 'Vatican City', code: 'VA', phoneCode: '+379' }
];

export const CITIES = {
  'Azerbaijan': [
    'Baku',
    'Ganja',
    'Sumgayit',
    'Mingachevir',
    'Lankaran',
    'Shirvan',
    'Shaki',
    'Yevlakh',
    'Nakhchivan',
    'Khankendi',
    'Naftalan',
    'Khirdalan',
    'Aghjabadi',
    'Aghdam',
    'Aghdash',
    'Aghstafa',
    'Aghsu',
    'Astara',
    'Babek',
    'Balakan',
    'Barda',
    'Beylagan',
    'Bilasuvar',
    'Jabrayil',
    'Jalilabad',
    'Julfa',
    'Dashkasan',
    'Fuzuli',
    'Gadabay',
    'Goranboy',
    'Goychay',
    'Goygol',
    'Hajigabul',
    'Khachmaz',
    'Khizi',
    'Khojaly',
    'Khojavend',
    'Imishli',
    'Ismayilli',
    'Kalbajar',
    'Kurdamir',
    'Lachin',
    'Lerik',
    'Masalli',
    'Neftchala',
    'Oghuz',
    'Ordubad',
    'Gabala',
    'Gakh',
    'Gazakh',
    'Gobustan',
    'Guba',
    'Gubadli',
    'Gusar',
    'Saatli',
    'Sabirabad',
    'Shabran',
    'Shahbuz',
    'Salyan',
    'Shamakhi',
    'Samukh',
    'Sharur',
    'Siyazan',
    'Shusha',
    'Tartar',
    'Tovuz',
    'Ujar',
    'Yardimli',
    'Zagatala',
    'Zardab',
    'Zangilan'
  ],
  'Turkey': [
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkari',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak'
  ],
  'Russia': [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Nizhny Novgorod',
    'Chelyabinsk',
    'Samara',
    'Omsk',
    'Rostov-on-Don',
    'Ufa',
    'Krasnoyarsk',
    'Voronezh',
    'Perm',
    'Volgograd',
    'Krasnodar',
    'Saratov',
    'Tyumen',
    'Tolyatti',
    'Izhevsk',
    'Barnaul',
    'Ulyanovsk',
    'Irkutsk',
    'Khabarovsk',
    'Yaroslavl',
    'Vladivostok',
    'Makhachkala',
    'Orenburg',
    'Tomsk',
    'Kemerovo',
    'Ryazan',
    'Naberezhnye Chelny',
    'Astrakhan',
    'Penza',
    'Kirov',
    'Lipetsk',
    'Balashikha',
    'Cheboksary',
    'Kaliningrad',
    'Tula',
    'Kursk',
    'Sevastopol',
    'Surgut',
    'Ulan-Ude',
    'Sochi',
    'Tver',
    'Ivanovo',
    'Bryansk',
    'Belgorod',
    'Vladimir',
    'Arkhangelsk',
    'Chita',
    'Kaluga',
    'Smolensk',
    'Kurgan',
    'Oryol',
    'Vologda',
    'Vladikavkaz',
    'Grozny',
    'Murmansk',
    'Tambov',
    'Petrozavodsk',
    'Kostroma',
    'Novorossiysk',
    'Yoshkar-Ola',
    'Taganrog',
    'Sterlitamak',
    'Petropavlovsk-Kamchatsky',
    'Syktyvkar',
    'Nalchik',
    'Shakhty',
    'Blagoveshchensk'
  ]
};
