/**
 * 3bucaq — Ölkələr, Telefon Kodları və Şəhərlər siyahısı
 */

export const COUNTRIES = [
  { name: 'Azərbaycan', code: 'AZ', phoneCode: '+994' },
  { name: 'Türkiyə', code: 'TR', phoneCode: '+90' },
  { name: 'Rusiya', code: 'RU', phoneCode: '+7' },
  { name: 'ABŞ', code: 'US', phoneCode: '+1' },
  { name: 'Almaniya', code: 'DE', phoneCode: '+49' },
  { name: 'Fransa', code: 'FR', phoneCode: '+33' },
  { name: 'Böyük Britaniya', code: 'GB', phoneCode: '+44' },
  { name: 'İtaliya', code: 'IT', phoneCode: '+39' },
  { name: 'İspaniya', code: 'ES', phoneCode: '+34' },
  { name: 'Kanada', code: 'CA', phoneCode: '+1' },
  { name: 'Gürcüstan', code: 'GE', phoneCode: '+995' },
  { name: 'Ukrayna', code: 'UA', phoneCode: '+380' },
  { name: 'Qazaxıstan', code: 'KZ', phoneCode: '+7' },
  { name: 'Özbəkistan', code: 'UZ', phoneCode: '+998' },
  { name: 'Türkmənistan', code: 'TM', phoneCode: '+993' },
  { name: 'Qırğızıstan', code: 'KG', phoneCode: '+996' },
  { name: 'Tacikistan', code: 'TJ', phoneCode: '+992' },
  { name: 'Belarus', code: 'BY', phoneCode: '+375' },
  { name: 'Moldova', code: 'MD', phoneCode: '+373' },
  { name: 'İran', code: 'IR', phoneCode: '+98' },
  { name: 'Səudiyyə Ərəbistanı', code: 'SA', phoneCode: '+966' },
  { name: 'BƏƏ', code: 'AE', phoneCode: '+971' },
  { name: 'Qətər', code: 'QA', phoneCode: '+974' },
  { name: 'Küveyt', code: 'KW', phoneCode: '+965' },
  { name: 'Bəhreyn', code: 'BH', phoneCode: '+973' },
  { name: 'Oman', code: 'OM', phoneCode: '+968' },
  { name: 'İordaniya', code: 'JO', phoneCode: '+962' },
  { name: 'Livan', code: 'LB', phoneCode: '+961' },
  { name: 'İraq', code: 'IQ', phoneCode: '+964' },
  { name: 'Suriya', code: 'SY', phoneCode: '+963' },
  { name: 'İsrail', code: 'IL', phoneCode: '+972' },
  { name: 'Polşa', code: 'PL', phoneCode: '+48' },
  { name: 'Çexiya', code: 'CZ', phoneCode: '+420' },
  { name: 'Slovakiya', code: 'SK', phoneCode: '+421' },
  { name: 'Macarıstan', code: 'HU', phoneCode: '+36' },
  { name: 'Rumıniya', code: 'RO', phoneCode: '+40' },
  { name: 'Bolqarıstan', code: 'BG', phoneCode: '+359' },
  { name: 'Yunanıstan', code: 'GR', phoneCode: '+30' },
  { name: 'Kipr', code: 'CY', phoneCode: '+357' },
  { name: 'Avstriya', code: 'AT', phoneCode: '+43' },
  { name: 'Belçika', code: 'BE', phoneCode: '+32' },
  { name: 'Niderland', code: 'NL', phoneCode: '+31' },
  { name: 'İsveçrə', code: 'CH', phoneCode: '+41' },
  { name: 'İsveç', code: 'SE', phoneCode: '+46' },
  { name: 'Norveç', code: 'NO', phoneCode: '+47' },
  { name: 'Danimarka', code: 'DK', phoneCode: '+45' },
  { name: 'Finlandiya', code: 'FI', phoneCode: '+358' },
  { name: 'İrlandiya', code: 'IE', phoneCode: '+353' },
  { name: 'Portuqaliya', code: 'PT', phoneCode: '+351' },
  { name: 'Hindistan', code: 'IN', phoneCode: '+91' },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92' },
  { name: 'Banqladeş', code: 'BD', phoneCode: '+880' },
  { name: 'Çin', code: 'CN', phoneCode: '+86' },
  { name: 'Yaponiya', code: 'JP', phoneCode: '+81' },
  { name: 'Cənubi Koreya', code: 'KR', phoneCode: '+82' },
  { name: 'Şimali Koreya', code: 'KP', phoneCode: '+850' },
  { name: 'Vyetnam', code: 'VN', phoneCode: '+84' },
  { name: 'Tailand', code: 'TH', phoneCode: '+66' },
  { name: 'İndoneziya', code: 'ID', phoneCode: '+62' },
  { name: 'Malayziya', code: 'MY', phoneCode: '+60' },
  { name: 'Sinqapur', code: 'SG', phoneCode: '+65' },
  { name: 'Filippin', code: 'PH', phoneCode: '+63' },
  { name: 'Avstraliya', code: 'AU', phoneCode: '+61' },
  { name: 'Yeni Zelandiya', code: 'NZ', phoneCode: '+64' },
  { name: 'Braziliya', code: 'BR', phoneCode: '+55' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Çili', code: 'CL', phoneCode: '+56' },
  { name: 'Kolumbiya', code: 'CO', phoneCode: '+57' },
  { name: 'Peru', code: 'PE', phoneCode: '+51' },
  { name: 'Venesuela', code: 'VE', phoneCode: '+58' },
  { name: 'Meksika', code: 'MX', phoneCode: '+52' },
  { name: 'Misir', code: 'EG', phoneCode: '+20' },
  { name: 'Cənubi Afrika Respublikası', code: 'ZA', phoneCode: '+27' },
  { name: 'Nigeriya', code: 'NG', phoneCode: '+234' },
  { name: 'Keniya', code: 'KE', phoneCode: '+254' },
  { name: 'Mərakeş', code: 'MA', phoneCode: '+212' },
  { name: 'Əlcəzair', code: 'DZ', phoneCode: '+213' },
  { name: 'Tunis', code: 'TN', phoneCode: '+216' },
  { name: 'Liviya', code: 'LY', phoneCode: '+218' },
  { name: 'Sudan', code: 'SD', phoneCode: '+249' },
  { name: 'Efiopiya', code: 'ET', phoneCode: '+251' },
  { name: 'Qana', code: 'GH', phoneCode: '+233' },
  { name: 'Anqola', code: 'AO', phoneCode: '+244' },
  { name: 'Mozambik', code: 'MZ', phoneCode: '+258' },
  { name: 'Madaqaskar', code: 'MG', phoneCode: '+261' },
  { name: 'Seneqal', code: 'SN', phoneCode: '+221' },
  { name: 'Zimbabve', code: 'ZW', phoneCode: '+263' },
  { name: 'Xorvatiya', code: 'HR', phoneCode: '+385' },
  { name: 'Serbiya', code: 'RS', phoneCode: '+381' },
  { name: 'Sloveniya', code: 'SI', phoneCode: '+386' },
  { name: 'Bosniya və Herseqovina', code: 'BA', phoneCode: '+387' },
  { name: 'Albaniya', code: 'AL', phoneCode: '+355' },
  { name: 'Şimali Makedoniya', code: 'MK', phoneCode: '+389' },
  { name: 'Monteneqro', code: 'ME', phoneCode: '+382' },
  { name: 'İslandiya', code: 'IS', phoneCode: '+354' },
  { name: 'Estoniya', code: 'EE', phoneCode: '+372' },
  { name: 'Latviya', code: 'LV', phoneCode: '+371' },
  { name: 'Litva', code: 'LT', phoneCode: '+370' },
  { name: 'Lüksemburq', code: 'LU', phoneCode: '+352' },
  { name: 'Malta', code: 'MT', phoneCode: '+356' },
  { name: 'Monako', code: 'MC', phoneCode: '+377' },
  { name: 'Andorra', code: 'AD', phoneCode: '+376' },
  { name: 'San-Marino', code: 'SM', phoneCode: '+378' },
  { name: 'Lixtenşteyn', code: 'LI', phoneCode: '+423' },
  { name: 'Vatikan', code: 'VA', phoneCode: '+379' }
];

export const CITIES = {
  'Azərbaycan': [
    'Bakı',
    'Gəncə',
    'Sumqayıt',
    'Mingəçevir',
    'Lənkəran',
    'Şirvan',
    'Şəki',
    'Yevlax',
    'Naxçıvan',
    'Xankəndi',
    'Naftalan',
    'Xırdalan',
    'Ağcabədi',
    'Ağdam',
    'Ağdaş',
    'Ağstafa',
    'Ağsu',
    'Astara',
    'Babək',
    'Balakən',
    'Bərdə',
    'Beyləqan',
    'Biləsuvar',
    'Cəbrayıl',
    'Cəlilabad',
    'Culfa',
    'Daşkəsən',
    'Füzuli',
    'Gədəbəy',
    'Goranboy',
    'Göyçay',
    'Göygöl',
    'Hacıqabul',
    'Xaçmaz',
    'Xızı',
    'Xocalı',
    'Xocavənd',
    'İmişli',
    'İsmayıllı',
    'Kəlbəcər',
    'Kürdəmir',
    'Laçın',
    'Lerik',
    'Masallı',
    'Neftçala',
    'Oğuz',
    'Ordubad',
    'Qəbələ',
    'Qax',
    'Qazax',
    'Qobustan',
    'Quba',
    'Qubadlı',
    'Qusar',
    'Saatlı',
    'Sabirabad',
    'Şabran',
    'Şahbuz',
    'Salyan',
    'Şamaxı',
    'Samux',
    'Şərur',
    'Siyəzən',
    'Şuşa',
    'Tərtər',
    'Tovuz',
    'Ucar',
    'Yardımlı',
    'Zaqatala',
    'Zərdab',
    'Zəngilan'
  ],
  'Türkiyə': [
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkari',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak'
  ],
  'Rusiya': [
    'Moskva',
    'Sankt-Peterburq',
    'Novosibirsk',
    'Yekaterinburq',
    'Kazan',
    'Nijni Novqorod',
    'Çelyabinsk',
    'Samara',
    'Omsk',
    'Rostov-na-Donu',
    'Ufa',
    'Krasnoyarsk',
    'Voronej',
    'Perm',
    'Volqoqrad',
    'Krasnodar',
    'Saratov',
    'Tümen',
    'Tolyatti',
    'İjevsk',
    'Barnaul',
    'Ulyanovsk',
    'İrkutsk',
    'Xabarovsk',
    'Yaroslavl',
    'Vladivostok',
    'Maxaçqala',
    'Orenburq',
    'Tomsk',
    'Kemerovo',
    'Ryazan',
    'Naberejnıye Çelnı',
    'Həştərxan',
    'Penza',
    'Kirov',
    'Lipetsk',
    'Balaşixa',
    'Çeboksarı',
    'Kalininqrad',
    'Tula',
    'Kursk',
    'Sevastopol',
    'Surqut',
    'Ulan-Ude',
    'Soçi',
    'Tver',
    'İvanovo',
    'Bryansk',
    'Belqorod',
    'Vladimir',
    'Arxangelsk',
    'Çita',
    'Kaluga',
    'Smolensk',
    'Kurqan',
    'Oryol',
    'Vologda',
    'Vladikavkaz',
    'Qroznı',
    'Murmansk',
    'Tambov',
    'Petrozavodsk',
    'Kostroma',
    'Novorossiysk',
    'Yoşkar-Ola',
    'Taqanroq',
    'Sterlitamak',
    'Petropavlovsk-Kamçatski',
    'Sıktıvkar',
    'Nalçik',
    'Şaxtı',
    'Blaveşçensk'
  ]
};
